@startuml music

class User {
  username
  password
  +sign_in()
}

class Group {
  name
}

class Member {
  roles
}

class PlayerSpawnerScript{

}

class EnemySpawnerScript{

}

class CharacterButtonScript{
  
}

class ButtonManagerScript{

}

class PlayerControllerScript{

}

class PlayerCoreScript{

}

class EnemyCoreScript{

}

class PlayerScript{

}

class EnemyControllerScript{

}

class StandScript{

}

class EnemyStandScript{

}

class BossScript{

}

class EnemyBulletScript{

}


class ItemScript{

}

class ItemSpawnerScript{

}


class LoadManager{

}

class WinOrLoseManager{

}


class SceneManagerScript{

}


class ButtonManagerScript{

}

class CharacterButtonScript{

}

class HowToPlayManagerScript{

}

class PauseScript{

}

class RetireButtonScript{

}


class AspectRatioManager{

}

class BlinkingImageScript{

}

class FieldOfViewScript{

}

class FireWorksManager{

}

class UIScaleScript{

}


class StageSelectManager{
  
}






User .. Member
Group .. Member

@enduml